name: CMake Test Workflow

on:
  pull_request:
    branches: [ "dev" ]
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/PULL_REQUEST_TEMPLATE.md"
      - ".gitignore"
      - ".prettierrc"
      - ".eslintrc"

env:
  # CMake 빌드 타입 설정 (Release, Debug 등)
  BUILD_TYPE: Release

jobs:
  cmake_test:
    runs-on: ubuntu-latest

    steps:
    # 1. 코드 체크아웃
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. CMake 설정을 수행하여 빌드 파일을 생성
    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DENABLE_COVERAGE=ON

    # 3. 빌드 수행
    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}}

    # 4. 테스트 실행
    - name: Test
      working-directory: build
      run: ctest -C ${{env.BUILD_TYPE}} -V
