name: Format Test Workflow

on:
  pull_request:
    branches: [ "dev" ]
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/PULL_REQUEST_TEMPLATE.md"
      - ".gitignore"
      - ".prettierrc"
      - ".eslintrc"

jobs:
  format-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run clang-format check
      uses: DoozyX/clang-format-lint-action@v0.14
      with:
        source: '.'  # 포맷 확인 대상 디렉토리 (현재 디렉토리)
        exclude: './third_party ./external'  # 검사 제외 디렉토리
        extensions: 'h,cc'  # 검사할 파일 확장자
        clangFormatVersion: 14
        style: file  # `.clang-format` 파일을 참조하도록 설정
